version: '3.1'

services:
  pyserv:
    restart: always
    build: ./sarima
    container_name: pyserv
    ports:
      - "5000:5000"
    expose:
      - "5000"
  db:
    image: postgres
    restart: always
    volumes:
      - "./sql/init:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_DB: expenses
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080